const profiles = [
    {
      name: 'Kiran Kumar',
      gender:'Male',
      age: 28,
      location: 'Trivandrum',
      religion: 'Hindu',
      caste: 'Nair',
      education: 'Masters',
      occupation: 'Engineer',
      annualIncome: '10 - 20 Lakhs',
      about: 'I am a simple and down-to-earth person.',
    },
    {
      name: 'Sneha Nair',
      gender:'Female',
      age: 25,
      location: 'Kochi',
      religion: 'Hindu',
      caste: 'Nair',
      education: 'Doctorate',
      occupation: 'Doctor',
      annualIncome: '20 - 50 Lakhs',
      about: 'I am passionate about my career in medicine.',
    },
    {
      name: 'Ajmal',
      gender:'Male',
      age: 30,
      location: 'Calicut',
      religion: 'Muslim',
      caste: 'Sunni',
      education: 'Bachelors',
      occupation: 'Business',
      annualIncome: 'Above 50 Lakhs',
      about: 'I am an entrepreneur running my own business.',
    },
    {
      name: 'Amrita',
      gender:'Female',
      age: 26,
      location: 'Thrissur',
      religion: 'Hindu',
      caste: 'Nair',
      education: 'Masters',
      occupation: 'Teacher',
      annualIncome: '5 - 10 Lakhs',
      about: 'I love teaching and working with children.',
    },
    {
      name: 'Anvin',
      gender:'Male',
      age: 32,
      location: 'Kollam',
      religion: 'Christian',
      caste: 'Roman Catholic',
      education: 'Masters',
      occupation: 'Engineer',
      annualIncome: '10 - 20 Lakhs',
      about: 'I enjoy traveling and exploring new places.',
    },
    {
      id: 6,
      name: 'Manoj Menon',
      gender:'Male',
      age: 32,
      location: 'Thrissur',
      religion: 'Hindu',
      caste: 'Menon',
      education: 'Ph.D',
      occupation: 'Professor',
      annualIncome: '25 - 40 Lakhs',
      about: 'I am passionate about teaching and research.',
    },
    {
      id: 7,
      name: 'Sangeetha',
      gender:'Female',
      age: 29,
      location: 'Kollam',
      religion: 'Hindu',
      caste: 'Nair',
      education: 'Masters',
      occupation: 'Banker',
      annualIncome: '18 - 30 Lakhs',
      about: 'I enjoy traveling and exploring new cultures.',
    },
    {
      id: 8,
      name: 'Alen',
      gender:'Male',
      age: 35,
      location: 'Alappuzha',
      religion: 'Christian',
      caste: 'Roman Catholic',
      education: 'Bachelor',
      occupation: 'Marketing Manager',
      annualIncome: '20 - 35 Lakhs',
      about: 'I am ambitious and enjoy outdoor activities.',
    },
    {
      id: 9,
      name: 'Divya ',
      gender:'Female',
      age: 26,
      location: 'Malappuram',
      religion: 'Hindu',
      caste: 'Thiyya',
      education: 'MBBS',
      occupation: 'Doctor',
      annualIncome: '30 - 50 Lakhs',
      about: 'I am dedicated to my profession and family.',
    },
    {
      id: 10,
      name: 'Vinod Pillai',
      gender:'Male',
      age: 31,
      location: 'Pathanamthitta',
      religion: 'Hindu',
      caste: 'Pillai',
      education: 'MBA',
      occupation: 'Financial Analyst',
      annualIncome: '22 - 38 Lakhs',
      about: 'I am analytical and enjoy solving complex problems.',
    },
    {
      id: 11,
      name: 'Joseph',
      gender:'Male',
      age: 28,
      location: 'Idukki',
      religion: 'Christian',
      caste: 'Syrian Christian',
      education: 'B.Tech',
      occupation: 'Software Developer',
      annualIncome: '15 - 25 Lakhs',
      about: 'I am creative and love experimenting with new technologies.',
    },
    {
      id: 12,
      name: 'Rajesh ',
      gender:'Male',
      age: 33,
      location: 'Palakkad',
      religion: 'Hindu',
      caste: 'Vishwakarma',
      education: 'LLB',
      occupation: 'Lawyer',
      annualIncome: '18 - 28 Lakhs',
      about: 'I am passionate about justice and legal advocacy.',
    },
    {
      id: 13,
      name: 'Deepa',
      gender:'Female',
      age: 30,
      location: 'Wayanad',
      religion: 'Hindu',
      caste: 'Menon',
      education: 'Masters',
      occupation: 'HR Manager',
      annualIncome: '20 - 35 Lakhs',
      about: 'I enjoy mentoring and developing talent within organizations.',
    },
    {
      id: 14,
      name: 'Teenu',
      gender:'Female',
      age: 29,
      location: 'Kottayam',
      religion: 'Christian',
      caste: 'Latin Catholic',
      education: 'Pharmacy',
      occupation: 'Pharmacist',
      annualIncome: '12 - 20 Lakhs',
      about: 'I am meticulous and detail-oriented in my work.',
    },
    {
      id: 15,
      name: 'Anjali Pillai',
      gender:'Female',
      age: 27,
      location: 'Ernakulam',
      religion: 'Hindu',
      caste: 'Pillai',
      education: 'MCA',
      occupation: 'Software Tester',
      annualIncome: '15 - 28 Lakhs',
      about: 'I am passionate about ensuring software quality and performance.',
    },
  ];
  
  
  module.exports = profiles;
  